In [7]:
#algorithm needleman wunsch
#import libraries
import numpy as np
#enter sequence use input to input data
seq1='ATAATTCA'
seq2='ATGGCTA'
#length of sequence
m = len(seq1)
n = len(seq2) 
#scoring matrix
score_matrix = np.zeros((m+1, n+1), dtype=int)
#scores
match=1
gap= mismatch= -1
score_matrix[0][0] = 0
#scoring condition
for i in range(0,m+1):
	score_matrix[i][0] = i * gap 
for j in range(0,n+1):
	score_matrix[0][j] = j * gap 
#making dictionary and conditioning for gap match and mismatch
def Align(x,y):
	if x==y:
		return match
	elif x!= y:
		return mismatch	
	elif x == '-' or y == '-':
		return gap	
#dictionary algorithm for filling matrix
def NeedlemanWunchScoring(seq1, seq2, n, m):
	#fill the other entries of the matrix
	for i in range(1, m+1):
		for j in range(1, n+1):
			match  = score_matrix[i-1][j-1] + Align(seq1[i-1], seq2[j-1])
			delete = score_matrix[i-1][j]   +  gap
			insert = score_matrix[i][j-1]   +  gap
			score_matrix[i][j] = max(match, delete, insert)
			#print seq1[i-1], seq2[j-1], score_mat[i-1][j-1]
	return score_matrix		

Final_matrix=NeedlemanWunchScoring(seq1, seq2, n, m)
#print results
print ("seq1=", seq1 +"\n" + "seq2=", seq2)

print ("score matrix")

print (Final_matrix)

seq1= ATAATTCA
seq2= ATGGCTA
score matrix
[[ 0 -1 -2 -3 -4 -5 -6 -7]
 [-1  1  0 -1 -2 -3 -4 -5]
 [-2  0  2  1  0 -1 -2 -3]
 [-3 -1  1  1  0 -1 -2 -1]
 [-4 -2  0  0  0 -1 -2 -1]
 [-5 -3 -1 -1 -1 -1  0 -1]
 [-6 -4 -2 -2 -2 -2  0 -1]
 [-7 -5 -3 -3 -3 -1 -1 -1]
 [-8 -6 -4 -4 -4 -2 -2  0]]
